# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fc3c629dc2def02811683888348e17b0b66cf885f2225a2ec238c20284f953a717d292859a2294ab54323ac0d7a783ff46aa868dca82cdbb095b99d2589726d

test:
  secret_key_base: 4a9b0a626e9e3de22757b3547888a2980049adec6d654e145004c7459f75747cc3ddfd4fea45fac3c9891810d2144475c5ad972ce802ed0fc8e4d613aa400f8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
